services:
  py2:
    build: ./src_py2
    command: python2 -i password.py 
    volumes:
      - ./src_py2:/src
    working_dir: /src 
    tty: true
    stdin_open: true
    networks:
      - my_network

  py3:
    build: ./src_py3
    networks:
      - my_network

networks:
  my_network:
    driver: bridge