services:
  py2:
    build: ./src
    command: python2 -i main.py 
    volumes:
      - ./src:/src
    working_dir: /src 
    tty: true
    stdin_open: true
    networks:
      - my_network

  py3:
    build: ./src_transcribe
    networks:
      - my_network

networks:
  my_network:
    driver: bridge